language: php

php:
  - 7.2.27
  - 7.3
  - 7.4

before_script: composer install

script:
  - vendor/bin/phpunit

after_script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/php-coveralls --exclude-no-stmt -v
